######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 28 17:00:17 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += dials.ui
SOURCES += main.cpp
